### ISSUE TITLE
Google Play cannot download anything

### ISSUE THREAD

**Issue by roviury** [iTXTech/Daedalus#37] opened 2017-09-04 04:58 UTC
As long as Daedalus is activated,  no matter how you set the DNS severs and rules,  no a single combination can let users to download/update apps in Google Play. (Only with a message "Downloading....") 
From the log,  there should be a request to android.clients.google.com

In other similar apps providing VPN services to non-root android devices,  like Transocks,  Google Play Download is not affected.

Please fix.

**Comment by roviury** [comment] 2017-09-04 05:02
I am a user outside GFW. I see similar problems from other users in Google Play comments as well.

It is possible to skip DNS setting for some websites ? it may help.

**Comment by PeratX** [comment] 2017-09-04 05:09
Maybe wrong IP returned by DNS Server.

**Comment by roviury** [comment] 2017-09-04 05:17
Impossible.  Try the top three DNS servers.  UltraDNS, OpenDNS and GoogleDNS.

I set them in the wifi router and my android can download/update in that wifi.

**Comment by roviury** [comment] 2017-09-04 05:19
The DNS is the same as my wifi router setting, all rules are removed.  Still cannot download/update

**Comment by tonbuta** [comment] 2017-09-04 05:50
Same problem. I found the errorMsg in download manager database (/data/data/com.android.providers.downloads/databases/downloads.db) is NAME_NOT_RESOLVED. Then I added an IP of android.clients.google.com in /etc/hosts, the errorMsg became ADDRESS_UNREACHABLE!  If it is the problem of wrong IP, it should be CONNECTION_TIMED_OUT. Google Play behaves as if there's no gateway.
When using same dnsmasq rule on my PC and setting DNS of my phone to my PC, Google play works fine.

**Comment by PeratX** [comment] 2017-09-04 10:10
I got it. I will release a beta version which have a new Debug option in Settings.
Turn it on and you can get the complete DNS Query Packet and DNS Response Packet in Log.

**Comment by PeratX** [comment] 2017-09-06 11:56
https://github.com/iTXTech/Daedalus/commit/89b9c0ef9568415f845ddc387da9a4b2c0433eee may help

**Comment by tonbuta** [comment] 2017-09-07 11:24
DNS resolving is OK. But the errorMsg is still 'unable to resolve host android.clients.google.com'. It seems android download manager cannot receive anything from VPN connection.
Log:
2017-09-07 13:57:33 [DEBUG] DNSMessage(32672 QUERY NO_ERROR resp[qr=1] rd ra)
[Q: android.clients.google.com.	IN	A]
[A: android.clients.google.com.	300	IN	A	216.58.200.192]
2017-09-07 13:57:33 [INFO] Provider: Resolving android.clients.google.com Type: A Sending to /119.23.248.241
2017-09-07 13:57:33 [DEBUG] DNSMessage(32672 QUERY NO_ERROR query[qr=0] rd)
[Q: android.clients.google.com.	IN	A]

**Comment by PeratX** [comment] 2017-09-07 11:46
But the response is correct. It seems SSL verify failed.

**Comment by roviury** [comment] 2017-09-17 10:12
Which configuration?

**Comment by PeratX** [comment] 2017-09-17 16:17
New hosts
111.111.111.111 android.clients.google.com

Import to Daedalus and see the reponse.

**Comment by tonbuta** [comment] 2017-09-17 17:02
After setting this rule, I can't see the download in download manager at all... And Google Play cancelled the download automatically after about five seconds. Then I added this rule directly in /etc/hosts and downloaded without Deadalus, it behaves the same way.
Log:
2017-09-18 00:44:47 [DEBUG] DNSMessage(28886 QUERY NO_ERROR resp[qr=1] rd)
[Q: android.clients.google.com.	IN	A]
[A: android.clients.google.com.	64	IN	A	111.111.111.111]
2017-09-18 00:44:47 [INFO] Provider: Resolved android.clients.google.com  Local resolver response: 111.111.111.111
2017-09-18 00:44:47 [DEBUG] DNSMessage(28886 QUERY NO_ERROR query[qr=0] rd)
[Q: android.clients.google.com.	IN	A]

**Comment by PeratX** [comment] 2017-09-17 22:57
Then the response should be correct.

**Comment by tonbuta** [comment] 2017-09-21 17:03
Finally I found the root cause after some search on Google. It's a bug of Download Manager on Nougat, and maybe also on Oreo. Just see
https://github.com/julian-klode/dns66/issues/31
https://issuetracker.google.com/issues/37105245
I changed only one line of code in Download Manager, from mNetwork.openConnection(url) to URL.openConnection(), then everything works!
So it totally has nothing to do with Daedalus, and other VPN apps which change DNS only also face the same problem.
But to fix Google Play downloads, maybe... something like a 'manual mode' could be added as a workaround. This mode just starts a local DNS server without activating VPN. Then we can set DNS manually. Or maybe in this mode Daedalus tunnels every package inside VPN connection like Shadowsocks.

**Comment by PeratX** [comment] 2017-09-23 15:44
Nice work!

**Comment by cubakcabak** [comment] 2017-10-08 17:01
how about implement a white list like others (blokada and dns66, for example).

or maybe add checking procedure to Daedalus code, skipping system download manager for api 25 and perhaps the later too.

**Comment by RazeSoldier** [comment] 2018-02-10 19:56
User within GFW

**Comment by PeratX** [comment] 2018-02-11 01:26
No. Governments now can detect SNIproxy, SS and SSR.

**Comment by Shennoter** [comment] 2018-02-14 15:40
SSR can be detected?So can we continue to use SSR?

**Comment by PeratX** [comment] 2018-03-03 01:11
Yes, you can. But there will a risk that the GFW can identify the SS(R) protocols and ban that ip address (I have two servers which have been banned).
When the ip address is banned, you won't be able to connect to the server just like google.

**Comment by PeratX** [comment] 2019-07-14 12:58
See App Filter

**Closed by PeratX** 2019-07-14 12:58 UTC
